/*
 * Stylesheets for the two shadow roots.
 *
 * Kept as strings rather than imported .css files so the modules stay loadable
 * without a bundler, which is what lets the DOM tests import them directly.
 */

export const BUTTON_CSS = [
  ':host { all: initial; }',
  'button {',
  '  display: inline-flex; align-items: center; gap: 6px;',
  '  height: 40px; padding: 0 14px; margin-left: 8px;',
  '  border: none; border-radius: 20px; cursor: pointer;',
  '  background: #333537; color: #e3e3e3;',
  '  font: 500 13px/1 "Google Sans", Roboto, -apple-system, sans-serif;',
  '}',
  'button:hover { background: #3f4144; }',
  'button[data-active="true"] { background: #a8c7fa; color: #062e6f; }',
  'svg { width: 18px; height: 18px; }',
  '.count {',
  '  min-width: 16px; padding: 0 4px; border-radius: 8px;',
  '  background: #f2b8b5; color: #601410; font-size: 11px; line-height: 16px;',
  '}'
].join('\n');

export const PANEL_CSS = [
  ':host { all: initial; }',
  '* { box-sizing: border-box; }',
  '.panel {',
  '  position: fixed; width: 340px; max-height: 70vh; /* overridden inline */',
  '  display: flex; flex-direction: column; overflow: hidden;',
  '  background: #1f2020; color: #e3e3e3; border: 1px solid #444746;',
  '  border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,.5);',
  '  font: 13px/1.45 "Google Sans", Roboto, -apple-system, sans-serif;',
  '  z-index: 2147483647;',
  '}',
  '.head { flex: none; display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 12px 14px 6px; }',
  '.head h2 { margin: 0; font-size: 14px; font-weight: 500; }',
  '.head-actions { display: flex; align-items: center; gap: 4px; }',
  '.chip { background: none; border: 1px solid #444746; border-radius: 14px; color: #9aa0a6;',
  '  cursor: pointer; font: inherit; font-size: 11px; padding: 3px 10px; }',
  '.chip:hover { background: #333537; color: #e3e3e3; }',
  '.icon-btn { background: none; border: 0; color: #9aa0a6; cursor: pointer; font-size: 18px;',
  '  line-height: 1; padding: 2px 6px; border-radius: 50%; }',
  '.icon-btn:hover { background: #333537; color: #e3e3e3; }',
  '.summary { flex: none; margin: 0; padding: 0 14px 8px; color: #9aa0a6; font-size: 12px; }',
  '.notice { margin: 0 14px 10px; padding: 8px 10px; border-radius: 8px;',
  '  background: #37331c; color: #f6e28a; font-size: 12px; }',
  '.list-head { display: flex; align-items: center; justify-content: space-between; padding: 0 14px 4px; }',
  '.check-all { display: flex; align-items: center; gap: 8px; cursor: pointer; font-size: 12px; }',
  '.muted { color: #9aa0a6; font-size: 11px; }',
  'ul { list-style: none; margin: 0; padding: 0 8px; }',
  '.row { display: flex; align-items: flex-start; gap: 10px; padding: 8px 6px; border-radius: 8px; }',
  '.row + .row { border-top: 1px solid #333537; border-radius: 0; }',
  '.row:hover { background: #292a2b; }',
  '.row.busy { background: rgba(168,199,250,.12); }',
  '.row.done { opacity: .55; }',
  '.row input { margin-top: 2px; flex: none; accent-color: #a8c7fa; }',
  '.row-body { min-width: 0; flex: 1; }',
  '.row-name { display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '.row-why { display: block; color: #9aa0a6; font-size: 11px; }',
  '.tag { display: inline-block; margin-left: 6px; padding: 0 6px; border-radius: 8px;',
  '  font-size: 10px; line-height: 15px; vertical-align: 1px; background: #333537; color: #9aa0a6; }',
  '.tag.known { color: #a8c7fa; }',
  '.tag.likely { color: #f6e28a; }',
  '.row-status { flex: none; font-size: 11px; color: #9aa0a6; }',
  '.row-status.ok { color: #6dd58c; }',
  '.row-status.err { color: #f2b8b5; }',
  'details { border-top: 1px solid #333537; margin-top: 8px; padding-top: 8px; }',
  'summary { cursor: pointer; padding: 0 14px 4px; color: #9aa0a6; font-size: 12px; }',
  '.hint { margin: 4px 14px 6px; color: #9aa0a6; font-size: 11px; }',
  /* The scrolling middle. min-height:0 is what lets a flex child actually
     shrink and scroll, instead of growing the panel past its max-height. */
  '.scroll { flex: 1 1 auto; min-height: 0; overflow-y: auto; }',
  '.scroll::-webkit-scrollbar { width: 8px; }',
  '.scroll::-webkit-scrollbar-thumb { background: #444746; border-radius: 4px; }',
  '.scroll::-webkit-scrollbar-thumb:hover { background: #5f6368; }',
  '.search { flex: none; padding: 0 14px 8px; }',
  '.search input {',
  '  width: 100%; padding: 6px 10px; border-radius: 8px;',
  '  background: #2a2b2c; border: 1px solid #444746; color: #e3e3e3;',
  '  font: inherit; font-size: 12px;',
  '}',
  '.search input:focus { outline: none; border-color: #a8c7fa; }',
  '.search input::placeholder { color: #8a8f94; }',
  '.empty { margin: 10px 14px 14px; color: #9aa0a6; font-size: 12px; }',
  '.hidden-note { color: #f6e28a; }',
  '.foot { flex: none; display: flex; align-items: center; gap: 10px;',
  '  padding: 10px 14px 12px; background: #1f2020; border-top: 1px solid #333537; }',
  '.primary { flex: 1; background: #a50e0e; border: 0; border-radius: 18px; color: #fff;',
  '  cursor: pointer; font: inherit; font-weight: 500; padding: 9px 12px; }',
  '.primary:hover:not(:disabled) { background: #c5221f; }',
  '.primary:disabled { background: #333537; color: #9aa0a6; cursor: default; }',
  '.link { background: none; border: 0; color: #a8c7fa; cursor: pointer; font: inherit; font-size: 12px; }',
  '.link:hover { text-decoration: underline; }'
].join('\n');
